####################################################################
## Playbook to install Prometheus Node Exporter on DISSLAB hosts ##
####################################################################
#
# REQUIREMENTS:
# - Install the required ansible roles.
#       $ ansible-galaxy install -r requirements.yml --force
# 
# RUNNING THIS PLAYBOOK:
#  
#  $ ansible-playbook -i ./hosts --private-key ~/.ssh/ansible-user -u ansible-user ansible-install-node-exporter.yml
#
# NOTES:
#
# Tested against Fedora 35.
# 


---
- name: Install Node Exporter
  hosts: all
  tags:
    - node_exporter
  become: true
  roles:
    - role: cloudalchemy.node-exporter
      meta: flush_handlers
  vars:
    - node_exporter_version: 1.3.1
  tasks:
    - name: Configure firewalld port for node exporter
      firewalld:
        port: 9100/tcp
        permanent: yes
        immediate: yes
        state: enabled