---
- hosts: elastic-master-nodes
  become: yes
  roles:
    - elastic-bootstrap-checks
    - { role: elastic.elasticsearch }
    - { role: geerlingguy.elasticsearch-curator }
  tasks:
    - name: Install OpenJDK 11 for RHEL-CENTOS
      yum:
        name: java-11-openjdk-devel
        state: latest
        update_cache: yes
       #cache_valid_time: 3600
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution == "CentOS"

    - name: Install OpenJDK 11 for Ubuntu
      apt:
        name: openjdk-11-jdk
        state: latest
        update_cache: yes
       #cache_valid_time: 3600
      when:
        - ansible_os_family == "Debian"
        - ansible_distribution == "Ubuntu"

- hosts: elastic-data-nodes
  become: yes
  roles:
    - elastic-bootstrap-checks
    - { role: elastic.elasticsearch }
  tasks:
    - name: Install OpenJDK 11 for RHEL-CENTOS
      yum:
        name: java-11-openjdk-devel
        state: latest
        update_cache: yes
       #cache_valid_time: 3600
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution == "CentOS"

    - name: Install OpenJDK 11 for Ubuntu
      apt:
        name: openjdk-11-jdk
        state: latest
        update_cache: yes
       #cache_valid_time: 3600
      when:
        - ansible_os_family == "Debian"
        - ansible_distribution == "Ubuntu"

- hosts: elastic-ingest-nodes
  become: yes
  roles:
    - elastic-bootstrap-checks
    - { role: elastic.elasticsearch }
  tasks:
    - name: Install OpenJDK 11 for RHEL-CENTOS
      yum:
        name: java-11-openjdk-devel
        state: latest
        update_cache: yes
       #cache_valid_time: 3600
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution == "CentOS"

    - name: Install OpenJDK 11 for Ubuntu
      apt:
        name: openjdk-11-jdk
        state: latest
        update_cache: yes
       #cache_valid_time: 3600
      when:
        - ansible_os_family == "Debian"
        - ansible_distribution == "Ubuntu"

- hosts: elastic-client-nodes
  become: yes
  roles:
    - elastic-bootstrap-checks
    - { role: elastic.elasticsearch }
  tasks:
    - name: Install OpenJDK 11 for RHEL-CENTOS
      yum:
        name: java-11-openjdk-devel
        state: latest
        update_cache: yes
       #cache_valid_time: 3600
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution == "CentOS"

    - name: Install OpenJDK 11 for Ubuntu
      apt:
        name: openjdk-11-jdk
        state: latest
        update_cache: yes
       #cache_valid_time: 3600
      when:
        - ansible_os_family == "Debian"
        - ansible_distribution == "Ubuntu"