---
- hosts: all
  name: Deploying Elasticsearch - prerequisite
  become: yes
  gather_facts: True
  vars_files:
  roles:
    - elastic-bootstrap-checks
    - java-open-jdk11

- hosts: all
  become: yes
  tasks:
    - name: Install OpenJDK 11 for RHEL-CENTOS
      yum:
        name: java-11-openjdk-devel
        state: latest
        update_cache: yes
       #cache_valid_time: 3600
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution == "CentOS"

    - name: Install OpenJDK 11 for Ubuntu
      apt:
        name: openjdk-11-jdk
        state: latest
        update_cache: yes
       #cache_valid_time: 3600
      when:
        - ansible_os_family == "Debian"
        - ansible_distribution == "Ubuntu"